/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clubs/{clubId}/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the club's form */
        get: operations["getFormByClub"];
        put?: never;
        /** Add form (only for demo and testing) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs/{clubId}/forms/{formId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FormDto: {
            clubId?: string;
            memberTypes?: components["schemas"]["MemberType"][];
            formId?: string;
            title?: string;
            /** Format: date-time */
            registrationOpens?: string;
        };
        MemberType: {
            id?: string;
            name?: string;
        };
        UserRegistration: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            memberTypeId: string;
            /** Format: date */
            dateOfBirth: string;
            phoneNumber: string;
        };
        RegistrationDto: {
            id?: string;
            clubId?: string;
            formId?: string;
            memberTypeId?: string;
            username?: string;
            email?: string;
            phoneNumber?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** Format: date-time */
            submittedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFormByClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormDto"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormDto"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clubId: string;
                formId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistration"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistrationDto"];
                };
            };
        };
    };
}
